### ISSUE TITLE
Video lag and stream interruptions on Android TV devices & Adding function subtitles and audio

### ISSUE THREAD

**Issue by azulmouad** [media-kit/media-kit#614]
Hello, I’m experiencing issues with your package. The video works well on mobile devices, but when I launch the app on Android TV devices, it lags and the stream videos stop and start. This issue is only present on Android TV, and I’m not sure why. Could it be because the player is not optimized for big screens?

Also, I have a request. Is it possible to add a function for subtitles and audio? I’m using stream video formats m3u8, and the URL has multiple subtitles and audios. Would it be possible to use your player for this?

**Comment by alexmercerind** [comment]
I'm kind of confused by the word lag now, is it:

- Jank in Flutter UI.
- Pauses due to buffering e.g. due to slow internet.
- Overall slowness or less frame-rate in video playback.

**Comment by alexmercerind** [comment]
> Adding function subtitles and audio.

Read documentation carefully & search there.

**Comment by azulmouad** [comment]
> I'm kind of confused by the word lag now, is it:
> 
> * Jank in Flutter UI.
> * Pauses due to buffering e.g. due to slow internet.
> * Overall slowness or less frame-rate in video playback.

When using the app on Android devices, the video experiences lag and buffering issues. Despite having a fast internet connection, the video plays smoothly on mobile devices, but the same content encounters problems when played on a television.

**Comment by azulmouad** [comment]
> > Adding function subtitles and audio.
> 
> Read documentation carefully & search there.

In your document, I discovered instructions on manually adding subtitles through a URL. However, on our end, we don't provide separate subtitle URLs; subtitles are embedded within the M3U8 or .MKV video URLs. When using VLC Player, it automatically decodes subtitles from the URL. I'm interested in knowing if your package provides a similar feature.

**Comment by azulmouad** [comment]
Hey AnyUpdates ?

**Comment by SpaceXM** [comment]
the lag in Android TV is a frame drop due to the use of flutter framework, i have used native bridge to solve the problem with a native player (i used amazon exoplayer) with custom ffmpeg module to support audio decode. I have tried soo many different pack to solve the problem but only native implementation solve this

**Comment by azulmouad** [comment]
> the lag in Android TV is a frame drop due to the use of flutter framework, i have used native bridge to solve the problem with a native player (i used amazon exoplayer) with custom ffmpeg module to support audio decode. I have tried soo many different pack to solve the problem but only native implementation solve this

If everything is satisfactory for you, could you please share the project on GitHub? It would greatly assist us, as we are still encountering these issues. Thank you very much.

**Comment by adam-hoang-vn** [comment]
Any update for this post? I met the same issue with author and don't have any solutions for it.

**Comment by alexmercerind** [comment]
Sorry no updates from my end. I don't have Android TV.

**Comment by adam-hoang-vn** [comment]
How about you? @azulmouad Do you have the solution for this issue?

**Comment by azulmouad** [comment]
> How about you? @azulmouad Do you have the solution for this issue?
> 
> 

No still facing same issues

**Comment by jeremylcarter** [comment]
I am using `media-kit` on Android TV and there is considerable frame loss. I will swap out with another player to isolate.

**Comment by bl1nch** [comment]
Hi, I'm trying to play FullHD video on my Android TV box but the performance is very slow. The video is glitchy and plays at about 10 fps. In addition, the `media.codec` loads the cpu at 100%.
`PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS`
`438 mediacodec   20   0 188M  68M  62M S 98.3   3.3  52:53.81 media.codec hw/android.hardware.media.omx@1.0-service`

**Comment by JulienDev** [comment]
@jeremylcarter @bl1nch could you please try to initialize VideoController with one of these configurations?

    const configuration = VideoControllerConfiguration(vo: 'mediacodec_embed', hwdec: 'mediacodec');
    OR
    const configuration = VideoControllerConfiguration(vo: 'gpu', hwdec: 'mediacodec');

    videoController = VideoController(player, configuration: configuration);

**Comment by jeremylcarter** [comment]
The video lag has gone with `const configuration = VideoControllerConfiguration(vo: 'gpu', hwdec: 'mediacodec');` on Android TV but now the audio is not playing. Ill get the exact codec information and post it.

**Comment by jeremylcarter** [comment]
Very strange the codec is AC3, so perhaps passthrough is not working?

**Comment by azulmouad** [comment]
> The video lag has gone with `const configuration = VideoControllerConfiguration(vo: 'gpu', hwdec: 'mediacodec');` on Android TV but now the audio is not playing. Ill get the exact codec information and post it.

If the Audio not playing try to test the app in a real device. i faced the same issues using Simulator .

**Comment by syleishere** [comment]
I can give an example of buffering issues or lack of being able to configure buffers...
https://mp3.sunsaturn.com/dog.mkv

Try loading that in video player and can see buffering issues...

Needs a way to buffer a bunch ahead of time, before playing...

**Comment by abdelaziz-mahdy** [comment]
> I can give an example of buffering issues or lack of being able to configure buffers... https://mp3.sunsaturn.com/dog.mkv
> 
> Try loading that in video player and can see buffering issues...
> 
> Needs a way to buffer a bunch ahead of time, before playing...

please test using latest github commit the cache problem should be fixed since it was set to auto not yes
```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```

**Comment by azulmouad** [comment]
I'm still encountering problems with video playback on the web. When I try to play the video, I only see a black screen. The video URL works fine on mobile and desktop platforms, but it seems to be incompatible with web browsers

http://raised27416.cdngold.me:80/4bf6f0714d0c/9ec8791592/639182

**Comment by abdelaziz-mahdy** [comment]
> I'm still encountering problems with video playback on the web. When I try to play the video, I only see a black screen. The video URL works fine on mobile and desktop platforms, but it seems to be incompatible with web browsers
> 
> http://raised27416.cdngold.me:80/4bf6f0714d0c/9ec8791592/639182

web support is limited as mentioned here 
https://github.com/media-kit/media-kit?tab=readme-ov-file#supported-formats

**Comment by syleishere** [comment]
I am actually wondering if you can install audio/video codecs on windows 11, whether web would then work as it uses native backend?

**Comment by alexmercerind** [comment]
The most efficient things can get on Android TV is --vo=mediacodec_embed + --hwdec=auto. Build against main branch.

**Comment by bl1nch** [comment]
> [@alexmercerind](https://github.com/alexmercerind), sorry for bothering. I tried to use the player with this configuration `(--vo=mediacodec_embed + --hwdec=auto)`. It works fine with some videos on Android TV, even 4k videos work without any lags. But some videos give some weird green screen. Do you know what could be the problem? I tried to play these videos as `rtp` streams and can provide sample files if needed.
> 
> ![Image](https://github.com/user-attachments/assets/0f3c3c5c-3b0a-4ce9-b7db-a822b1ae46a3)

I also tested this with media_kit: 1.1.11, since in 1.2.0 this configuration seems to be broken, as it has no effect

**Comment by syleishere** [comment]
Have to switch it back for other media types I noticed, but crappy cpu on Google tv streamer won't take normal mode without lag on 4k videos then. Solution is probably just do what you are doing and use handbrake to convert videos you have with green screen to av1

**Comment by syleishere** [comment]
Yeah I know, annoys me to, only work around I see is leaving it at defaults, then use those options to play demanding videos like 4k.

Any reason you not streaming av1? Idea is in next 5 years when everyone updates their devices everything will be av1.

**Comment by alexmercerind** [comment]
I will not really recommend you to ship `--vo=mediacodec_embed` in production. It is highly performant, but it may not work at all on some chipsets. The most I can recommend personally is to have on Android is `--vo=gpu` + `--hwdec=auto`.

https://github.com/media-kit/media-kit/blob/2493429cfdcbb3d0b4868cef70342cdc7c55d28a/media_kit_video/lib/src/video_controller/platform_video_controller.dart#L84-L89

**Comment by bl1nch** [comment]
> I will not really recommend you to ship `--vo=mediacodec_embed` in production. It is highly performant, but it may not work at all on some chipsets. The most I can recommend personally is to have on Android is `--vo=gpu` + `--hwdec=auto`.
> 
> [media-kit/media_kit_video/lib/src/video_controller/platform_video_controller.dart](https://github.com/media-kit/media-kit/blob/2493429cfdcbb3d0b4868cef70342cdc7c55d28a/media_kit_video/lib/src/video_controller/platform_video_controller.dart#L84-L89)
> 
> Lines 84 to 89 in [2493429](/media-kit/media-kit/commit/2493429cfdcbb3d0b4868cef70342cdc7c55d28a)
> 
>    /// Sets the [`--hwdec`](https://mpv.io/manual/stable/#options-hwdec) property on native backend. 
>    /// 
>    /// Default: Platform specific. 
>    /// * Windows, GNU/Linux, macOS & iOS : `auto` 
>    /// * Android: `auto-safe` 
>    final String? hwdec; 
> You may also try to update mpv & FFmpeg versions... I can't really guide, just have a look at the code.

Thanks for your answer, but I have the same problem with `--vo=gpu` + `--hwdec=auto`, the same video output with green frames. Maybe because the same `mediacodec` is used for decoding? Are there any ways to solve this?

![Image](https://github.com/user-attachments/assets/2783a6bb-413c-49e0-9a9d-6ea5788a7f33)

**Comment by syleishere** [comment]
Have you tried running it with mpv from command line first to see what it plays fine with first?

**Comment by bl1nch** [comment]
> Have you tried running it with mpv from command line first to see what it plays fine with first?

No, I haven't tried passing different parameters, but I just checked, and in the mpv-android app with the `use hardware acceleration` option checked, I get the same thing, the same green frames of video. Looks like this is definitely not a media_kit problem, I'll open an issue in mpv-android

**Comment by bl1nch** [comment]
@alexmercerind sorry, could you please make a build of https://github.com/media-kit/libmpv-android-video-build using the same versions of `mpv` `ffmpeg` and other dependencies as in the latest release of `mpv-android` (https://github.com/mpv-android/mpv-android/releases/tag/2025-04-21)? I did tests with `mpv-android` native app and in the latest version only `mediacodec-copy` does not work, and the configuration `--vo=mediacodec_embed + --hwdec=mediacodec` works quite stably

**Comment by Alhmiktmi** [comment]
@alexmercerind I have the same problem with green video frames on some Android TV boxes with some content. Have you managed to make any progress with the test build with libs from the latest mpv-android? Is there any way to test this?

**Comment by Spark-NV** [comment]
dang, sadly i also have just ran into this after attempting to migrate my app to medit_kit. hoping for a fix some day as media_kit appears to be the most feature rich video player app for flutter.

**Comment by DorisGM** [comment]
> [@alexmercerind](https://github.com/alexmercerind) sorry, could you please make a build of https://github.com/media-kit/libmpv-android-video-build using the same versions of `mpv` `ffmpeg` and other dependencies as in the latest release of `mpv-android` (https://github.com/mpv-android/mpv-android/releases/tag/2025-04-21)? I did tests with `mpv-android` native app and in the latest version only `mediacodec-copy` does not work, and the configuration `--vo=mediacodec_embed + --hwdec=mediacodec` works quite stably

@bl1nch  hi do you build media-kit  by yourself. I need to upgrade mpv too . Could you provide how to build it ? thanks

**Comment by AmarnathCJD** [comment]
Hi guys any update regarding this ?

**Comment by bl1nch** [comment]
**UPDATE:**

The `vo=mediacodec_embed` + `hwdec=mediacodec` configuration will **not** work on Android TV devices powered by **Amlogic** chipsets due to a decoder initialization error. 

A similar underlying issue with texture rendering and Amlogic decoders is being tracked here: https://github.com/flutter/flutter/issues/155355

As a potential workaround, switching from standard texture rendering to **platform view** might help resolve this issue
