### ISSUE TITLE
[ ISSUE ] - Problem getting monitor brightness WINDOWS 

### ISSUE THREAD

**Issue by atulkumar6556** [media-kit/media-kit#862]
on building in release mode for windows getting this issue . how to fix that -

**package:media_kit_libs_windows_video registered.
Problem getting monitor brightness**

@saini123hitesh@gmail.com
@abdelaziz-mahdy

**Comment by azulmouad** [comment]
same error
package:media_kit_libs_windows_video registered.
Problem getting monitor brightness

**Comment by zhaofeixaing** [comment]
same error
I am using flutter 3.19.5  
Is there any solution?

**Comment by atulkumar6556** [comment]
@azulmouad  @zhaofeixaing --  Is your issue resolved ??

**Comment by azulmouad** [comment]
> @azulmouad @zhaofeixaing -- Is your issue resolved ??

No still facing same issues

**Comment by imshobhitbajpai** [comment]
I tried the to copy the media kit dll files from Debug to Release and it worked on my pc but then on other PCs, I found the issue, msvcp140d.dll not found while installing.

**Comment by Roshan0511** [comment]
Facing same error

**package:media_kit_libs_windows_video registered.
Problem getting monitor brightness**

**Comment by atulkumar6556** [comment]
> I tried the to copy the media kit dll files from Debug to Release and it worked on my pc but then on other PCs, I found the issue, msvcp140d.dll not found while installing.

i have done same ,copied all media-kit files to release but it didn't  worked .

**Comment by abdelaziz-mahdy** [comment]
I don't know the issue sadly, and from my understanding that the brightness log is for the brightness package and it should not be an issue

**Comment by atulkumar6556** [comment]
![error_player](https://github.com/media-kit/media-kit/assets/48856680/0a989d76-47d1-4e5f-af9d-3ddf82f4f85c)

getting this issue ----

@abdelaziz-mahdy

**Comment by abdelaziz-mahdy** [comment]
> ![error_player](https://private-user-images.githubusercontent.com/48856680/346876195-0a989d76-47d1-4e5f-af9d-3ddf82f4f85c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTM3NjcsIm5iZiI6MTcyMDUxMzQ2NywicGF0aCI6Ii80ODg1NjY4MC8zNDY4NzYxOTUtMGE5ODlkNzYtNDdkMS00ZTVmLWFmOWQtM2RkZjgyZjRmODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA4MjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZGI5N2RhODM5ZDFhMDY5ZjY3YWY1MmYyODIyZmRhMDRlNDkwOGE0NGRlNWUyYWFhYzM0NmEwMmU0MzdmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CoYT7WnKrXVnYQfYOTwZvoK1EX8y2I9RrslOamcjIM)
> 
> getting this issue ----
> 
> @abdelaziz-mahdy

its a warning, and as it says `media_kit_native_event_loop: ^1.0.8` is missing from your pubspec

**Comment by atulkumar6556** [comment]
@abdelaziz-mahdy   on release mode example app also crash

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy   on release mode example app also crash

I don't know why and don't have a fix

**Comment by atulkumar6556** [comment]
> Facing same error
> 
> **package:media_kit_libs_windows_video registered. Problem getting monitor brightness**


Check your Visual Studio version : ---
THIS ISSUE CAN BE RESOLVED BY RE-INSTALLING    ( Visual STUDIO )
 * INSTALL CORRECT WIND-SDK 
 * open project ->
 # RUN 
 *  flutter clean  
 * flutter pub get 
 * flutter pub outdated 
 # Release
 * flutter build windows  

Should you find this useful, feel free to follow us on Github:

[https://github.com/atulkumar6556](url)

@azulmouad @Roshan0511 @zhaofeixaing @imshobhitbajpai

**Comment by SahajRana** [comment]
Is this resolved. You can find this issue when you one the app in different system. @atulkumar6556, @abdelaziz-mahdy

**Comment by abdelaziz-mahdy** [comment]
I merged pr 900 , since people confirmed it, try again it may show another problem, also don't copy the dlls,

How do you deliver your app?

**Comment by SahajRana** [comment]
It is now working for me. Thanks!

**Comment by BTMuli** [comment]
> 👉pr900 Workaround for broken windows builds #900

After upgrade to media_kit 1.1.11 and rebuild profile after clean,the terminal still shows the error:

```
√ Built build\windows\x64\runner\Profile\bangumi_today.exe
package:media_kit_libs_windows_video registered.
Problem getting monitor brightness
```

**Comment by alexmercerind** [comment]
Also... try to understand the difference between:
- Logging
- Warning
- Exception
- Error
